atls/raijin

packages/actl-precommit/src/config/lint-staged.config.ts

affects: @atlantis-lab/actl-precommit
ISSUES CLOSED: #100

fix(actl-precommit): change config export method

---

packages/actl-commitmsg/package.json
yarn.lock

affects: @atlantis-lab/actl-commitmsg
ISSUES CLOSED: #103

chore(actl-commitmsg): update commitlint dependency

---

packages/actl-lint/package.json
yarn.lock

affects: @atlantis-lab/actl-lint
ISSUES CLOSED: #104

chore(actl-lint): update @atlantis-lab/config

---

package.json
packages/actl/package.json

affects: @atlantis-lab/actl
ISSUES CLOSED: #107

chore(actl): update config dependency

---

packages/actl-build/package.json
packages/actl-check/package.json
packages/actl-commit/package.json
packages/actl-commitmsg/package.json
packages/actl-generator/package.json
packages/actl-precommit/package.json
packages/actl-test/package.json
packages/actl-typecheck/package.json
yarn.lock

affects: @atlantis-lab/actl-build, @atlantis-lab/actl-check, @atlantis-lab/actl-commit,
@atlantis-lab/actl-commitmsg, @atlantis-lab/actl-generator, @atlantis-lab/actl-precommit,
@atlantis-lab/actl-test, @atlantis-lab/actl-typecheck
ISSUES CLOSED: #109

chore: update @atlantis-lab/config in all packages

---

.gitignore
packages/actl-lint/package.json
yarn.lock

affects: @atlantis-lab/actl-lint
- Also added oclif.manifest.json to .gitignore
ISSUES CLOSED: #113

fix(actl-lint): reduce eslint version

---

packages/actl-commitmsg/src/commands/commitmsg.ts

affects: @atlantis-lab/actl-commitmsg
ISSUES CLOSED: #103

fix(actl-commitmsg): rewrite execa import to cjs

---

packages/actl-test/package.json
yarn.lock

affects: @atlantis-lab/actl-test
ISSUES CLOSED: #116

chore(deps): upgrade jest from 24.9.0 to 26.6.3

---

packages/actl-cr-publisher/src/commands/publish.ts

affects: @atlantis-lab/actl-cr-publisher
ISSUES CLOSED: #142

fix(actl-cr-publisher): handle async function correctly

---

packages/actl-lint/__tests__/lint.test.ts
packages/actl-lint/__tests__/mocks/bad-lint.ts
packages/actl-lint/__tests__/mocks/pass-lint.ts
packages/actl-lint/__tests__/tsconfig.json
packages/actl-lint/tsconfig.json

feat(actl-test): add a test

---

packages/actl-typecheck/__tests__/mocks/bad-typecheck.ts
packages/actl-typecheck/__tests__/mocks/pass-typecheck.ts
packages/actl-typecheck/__tests__/tsconfig.json
packages/actl-typecheck/__tests__/typecheck.test.ts

feat(actl-typecheck): add a test

---

packages/actl-build/package.json
packages/actl-check/package.json
packages/actl-commit/package.json
packages/actl-commitmsg/package.json
packages/actl-format/CHANGELOG.md
packages/actl-format/__tests__/format.test.ts
packages/actl-format/__tests__/mocks/pretty.ts
packages/actl-format/__tests__/mocks/ugly.ts
packages/actl-format/package.json
packages/actl-format/src/commands/format.ts
packages/actl-format/tsconfig.json
packages/actl-generator/package.json
packages/actl-lint/package.json
packages/actl-precommit/package.json
packages/actl-test/__tests__/mocks/mock-another-pass.mock-test.ts
packages/actl-test/__tests__/mocks/mock-fail.mock-test.ts
packages/actl-test/__tests__/mocks/mock-pass.mock-test.ts
packages/actl-test/__tests__/test.test.ts
packages/actl-test/package.json
packages/actl-typecheck/package.json
packages/actl/package.json
yarn.lock

feat(actl-format): add a test

---

packages/actl-cr-publisher/src/github.ts

affects: @atlantis-lab/actl-cr-publisher
ISSUES CLOSED: #142

fix(actl-cr-publisher): changed ref string transformation logic

---

.github/workflows/checks.yml

chore(ci): update action references

---

.github/actions/commit/action.yml
README_RU.md

- **chore(common): readme ru start command**
- **fix(github): commit file pattern**

Chore: readme and github

---

code/code-worker-utils/package.json
yarn.lock

Sync: code-worker-utils dependencies

---

config/eslint/src/index.ts

относится к https://github.com/atls/raijin/issues/442

fix(eslint): build

---

code/code-test/src/tester.ts

closes https://github.com/atls/raijin/issues/448

feat(test): accept filenames and file paths

---

yarn/plugin-checks/sources/checks-typecheck.command.tsx

относится к https://github.com/rees46/development/issues/2218

fix(checks): typecheck promises

---

yarn/plugin-checks/sources/checks-run.command.ts

относится к https://github.com/rees46/development/issues/2218

fix(checks): wait for all promises to be settled

---

code/code-pack/src/pack.interfaces.ts
code/code-pack/src/pack.ts
yarn/plugin-image/sources/image-pack.command.ts

closes https://github.com/atls/raijin/issues/456

refactor(pack): use code-pack, add more options for buildpack

---

code/code-commit/src/commit.linter.ts
yarn/plugin-commit/sources/commit-message-lint.command.ts

closes https://github.com/atls/raijin/issues/424

feat(code-commit): support getting project scopes

---

.pnp.cjs
.yarn/unplugged/@esbuild-linux-x64-npm-0.23.1-e5d2d8764d/node_modules/@esbuild/linux-x64/README.md
.yarn/unplugged/@rollup-rollup-linux-x64-gnu-npm-4.21.2-65bebf97f0/node_modules/@rollup/rollup-linux-x64-gnu/README.md
code/code-test/src/tester.ts
yarn.lock
yarn/plugin-test/package.json
yarn/plugin-test/sources/abstract-test.command.tsx
yarn/plugin-test/sources/test.command.ts
yarn/plugin-test/sources/test.plugin.ts

относится к https://github.com/atls/raijin/issues/469

feat(code-test): general test command, tap output

---

code/code-service/src/webpack.config.ts
yarn/plugin-commit/sources/commit-staged.command.ts

closes https://github.com/atls/raijin/issues/501

fix(code-commit): max arg length

---

code/code-service/src/webpack.config.ts

part of https://github.com/rees46/development/issues/2858

fix(code-service): chunk output format

---

code/code-service/src/webpack.config.ts

part of https://github.com/rees46/development/issues/2858

revert(code-service): hmr chunk format
